### ISSUE TITLE
A couple of questions about epitome

### ISSUE THREAD

**Issue by aigoyal** [josephdviviano/epitome#11]
Hi Joseph,
1. Everytime one generates a pipeline using `epitome check`, this creates an instance of a pipeline in the user's home directory. But, this copy of pipeline in the user's home directory is not referenced when the the pipeline is generated or executed ... correct?
2. I wanted to skip the T1 processing in freesurfer, so tried to add a module called `init_t1-basic` that is listed in the list of modules while one is building the pipeline. Pipeline generation immediately crashes with the following error:
   
    option #: 9
   Traceback (most recent call last):
   File "/srv/CODE/epitome/bin/epitome", line 764, in <module>
     run_epitome()
   File "/srv/CODE/epitome/bin/epitome", line 665, in run_epitome
     line, output = eval(command)
   File "<string>", line 1, in <module>
   AttributeError: 'module' object has no attribute 'init_t1'

Any thoughts?

**Comment by josephdviviano** [comment]
Hi Aman,
1. Pipelines are created using `epitome run`, not `epitome check`.
2. Every time the `master` script is executed (the thing generated by `epitome run`), it regenerates the `proclist` and `cmd` files using the modules in the `/home` directory.
3. Yes, that module (and a few others) don't have `command.py` modules yet, so they won't work via `epitome run` (though you could manually edit a `master` script to get them to work at the moment.
