### ISSUE TITLE
epitome failed for IMOB during registrations

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#23]
My epitome failed. 

/projects/colin/epitome/IMOB-COLIN/

Here is where in the log I think it failed:

---

```
           FSL: Linear registration pathway calculator
```

   Calculates EPI <--> T1 <--> MNI152 (included in AFNI distribution)
- Using data quality: high,
- Cost function: corratio,
- Degrees of freedom preset 6,
- Generates EPI template registered to T1 & vice-versa (sessionwise),

---

Image Exception : #22 :: ERROR: Could not open image /projects/colin/epitome/IMOB-COLIN/H160_CAMH/T1/SESS01/anat_T1_brain

---

It assumes the anat is called anat_T!_brain I guess. 

the contents of that folder are:

anat_aparc2009_fs.nii.gz  anat_aparc_fs.nii.gz  anat_T1_fs.nii.gz  

I am not sure if freesurfer was supposed to spit out anat_T!_brain?

**Comment by josephdviviano** [comment]
from your proclist, what does the output of epi-fsexport say? anat_T1_fs.nii.gz  should be converted to anat_t1_brain using AFNI (is AFNI available?)

**Comment by colinhawco** [comment]
You mean this file? It has an error in it but I am unclear.

-bash: module: line 1: syntax error: unexpected end of file
-bash: error importing function definition for `module'
/bin/bash: module: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for`module'

But it looks to me like freesurfer failed? The freesurfer outputs went
to /projects/colin/freesurfer. I can't see obvious issues (there are files
in there), but I am not at all familiar with freesurfer.

**Comment by josephdviviano** [comment]
Hi Colin, freesurfer worked. The conversion of the freesurfer oriented t1 to Afni oriented t1 failed. Is Afni installed properly? Where are you running this?

**Comment by colinhawco** [comment]
We were running on Anne's old machine which is tesla I believe. AFNi will
run on it but as you may recall we made a setup file for epitome which
called the relevant modules. But I can't remember where that setup file
was!

**Comment by josephdviviano** [comment]
how are you tryibng to run epitome? I just ran the epi-fsexport line from your proclist with no issues.

**Comment by josephdviviano** [comment]
exact command:

```
 epi-fsexport /projects/colin/epitome IMOB-COLIN
```

from: 

```
/projects/colin/epitome/IMOB-COLIN/proclist_150724_161704_150724-colinexample.sh
```

**Comment by josephdviviano** [comment]
Update?

**Comment by colinhawco** [comment]
I will take another look tomorrow.

**Comment by josephdviviano** [comment]
I'm closing this as it seems like things are working out on your end?
