### ISSUE TITLE
Bug: linreg_fs2epi_fsl failes if it is run after nonlinreg_calc_fsl

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#33]
Just an FYI, I don't know how to make this a bug report instead of an issue. I resolved it so it is not outstanding. 

Just do you know, linreg_fs2epi_fsl failes if it is run after nonlinreg_calc_fsl. 

Here was my original master:
. ${DIR_PIPE}/epitome/modules/pre/init_epi high 4 on alt+z off normal FSL >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/linreg_calc_fsl high corratio 6 >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/nonlinreg_calc_fsl >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/linreg_fs2epi_fsl >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/filter scaled 3 on off off on off off off 3 EPI_mask >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/lowpass filtered EPI_mask butterworth 0.1 >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/nonlinreg_epi2mni_fsl lowpass 3.0 >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}
. ${DIR_PIPE}/epitome/modules/pre/volsmooth MNI-nonlin EPI_mask_MNI-nonlin 10.0 multimask >> ${DIR_DATA}/${DIR_EXPT}/${SUB}/${CMD}

Here is the error, in linreg_fs2epi_fsl
**\* MODULE: linreg_fs2epi_fsl. Puts freesurfer atlases in EPI space. ***
Could not open matrix file /projects/colin/epitome/IMOB-COLIN/H011_CAMH/IMOB/SESS01/mat_T1_to_EPI.mat
terminate called after throwing an instance of 'NEWMAT::IncompatibleDimensionsException'
/projects/colin/epitome/IMOB-COLIN/H011_CAMH/cmd_151002_112335_nonlin-comp-filt.sh: line 354: 17218 Aborted                 flirt -in ${DIR_T1}/anat_aparc_brain.nii.gz -ref ${DIR}/anat_EPI_brain.nii.gz -applyxfm -init ${DIR}/mat_T1_to_EPI.mat -interp nearestneighbour -out ${DIR}/anat_aparc_reg.nii.gz

I moved linreg_fs2epi_fsl to just before nonlinreg_calc_fsl, and it works.

**Comment by josephdviviano** [comment]
Thanks Colin, I'll look into this.

**Comment by josephdviviano** [comment]
I'm not sure this is a replicate-able issue -- nonlinreg_calc_fsl only runs a single call to FNIRT do it must be something else.
