### ISSUE TITLE
T1 template wasn't copied into my epitome copy..

### ISSUE THREAD

**Issue by edickie** [josephdviviano/epitome#35]
I ran into this error...
- cp /home/edickie/epitome/ewd/assets/MNI152_T1_1mm_brain.nii.gz /projects/edickie/analysis/epitome/RTMSWM_test/data/anat_MNI.nii.gz
  cp: cannot stat ‘/home/edickie/epitome/ewd/assets/MNI152_T1_1mm_brain.nii.gz’: No such file or directory

(there is no /home/edickie/epitome/ewd/assets/...)

**Comment by josephdviviano** [comment]
Hi Erin, why is 'ewd' in the path?

**Comment by edickie** [comment]
That the name i gave to the pipeline...

**Comment by josephdviviano** [comment]
Oh, I see, the new location for the T1 is in your home directory, and you tried to run this through the queue or on another machine...

**Comment by josephdviviano** [comment]
Nope I'm wrong, the source for epitome wasn't copying the assets folder. That's changed now, if you want to pull the latest commit (check the diff :) )

Aside: you might have more luck on our particular system if you make the epitome folder in your home folder a symlink to somewhere in your projects folder, so all the machines can see this code.

**Comment by edickie** [comment]
I was running it on the same machine...(but that will be an issue when I
scale up and start using the queue..). It seems more like whatever is
making a copy of epitome into my home folder isn't copying the assets...

**Comment by josephdviviano** [comment]
Yes check my last commit i fixed the bug (I wasn't copying the assets folder to the home directory).
