### ISSUE TITLE
epi-randomize and covariate interactions

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#52]
Sonja is running an interaction analysis on a covariate between groups. To do the interaction, the covariate is split into two columns, with zeros entered for the subjects in the other groups. For example:

1 0  -2 0
1 0  -1 0
1 0  -1 0
1 0   1 0
0 1  0  2
0 1 -0  1
0 1  0  1
0 1  0 1

Where column 1 if group1, column 2 is group2, columns three is the covariate in group1, and column four is the covariate in group two. 

She is under the impression epi-randomise is currently mean-centering columns 3 and 4 separately. This is not correct. When analyzing an interaction of a covariate, the covariate should be mean-centered across ALL subjects, then split into two columns. 

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/GLM#Two_Groups_with_continuous_covariate_interaction

I didn't check this myself, so maybe it is correct and Sonja misunderstood the code.

**Comment by josephdviviano** [comment]
Moved here. https://github.com/josephdviviano/fslpal/issues/2
