### ISSUE TITLE
 MODULE: linreg_fs2epi_fsl typo

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#58]
if [ ${multisession} -eq 1 ]; then
        DIR_T1="${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}"
    else
        DIR_T1="${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/SESS01)"
    fi

Not in the else, there is a ")" instead of a "/"

**Comment by josephdviviano** [comment]
Thanks @colinhawco , nice catch, fixed in latest commit 80bd3f8
