### ISSUE TITLE
filter order

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#59]
If psyio regressors are in place filter fails. After the -LHS portion it appends the -ort<physio> I think maye this needs to be moved down tot he end, the -ort can't go there.

like:
3dTfitter -prefix ${SESS}/func_noise_betas.${ID}.${NUM}.nii.gz -fitts ${SESS}/func_noise.${ID}.${NUM}.nii.gz -polort 0 -RHS ${SESS}/func_tmp_det.${ID}.${NUM}.nii.gz -LHS 

if [ -f ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D ]; then
              CMD="${CMD} -ort ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D"
 fi
this can't follow right after the initial CMD command because it uses the -ort flag.

**Comment by josephdviviano** [comment]
Good catch @colinhawco -- I'll look into it

**Comment by josephdviviano** [comment]
OK, I the `-ort` was from the old AFNI tool I was using to do filtering. `3dTfitter` does not use `-ort`. I've just removed it ... you should be good to go.

FYI I also added a module for running ICA_AROMA.py (it's called `ica_aroma`), which is a fully-automated way of using ICA to regress head motion from the data. You might want to experiment with it for your task data!
